---
title: "Assignment 1: Introduction"
author: "Julia Kagiliery"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have taken undergraduate and graduate course in R at Duke including professor Luana's 797 timeseries course. I am confident in my ability to handle basic analystics and discover new functions. I have used Git before but want to figure out how to more seemlessly have multiple projects and repositories so I can work between my personal projects (saved currently in my google drive) and course projects. I also work with R and analytics in my assistantship.

2. Are there any components of the course about which you feel confident?

> Answer: I am confident in my data tidying and visuakization skills for certain types of data. I do have R and data visualization experience (enough to be dangerous, but it could certainly use some work) but I am looking forward to a refresher and to become more efficient in my code. I tend to take a brute force method when coding. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I would say the only thing I feel super apprehensive about would be the class fomrat. I tend to not enjoy filpped classrooms do to the large share of recorded lectures and videos; I often times do not find virtual classes super engaging. I am very much looking forward to learning more about geographic data in this course.  


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/juliakagiliery/EDA_Spring2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
